defmodule Vinmar.Migration do
  def test do
    "/Users/rubenbaezacolin/Downloads/FA_test.xlsx"
    |> build_data()
    |> IO.inspect(label: "LIST -------> ")

    # multi_init = Carbonite.Multi.insert_transaction(Ecto.Multi.new(), %{})
  end

  defp build_data(path) do
    {:ok, package} = XlsxReader.open(path)

    package
    |> XlsxReader.sheet_names()
    |> Enum.map(&build_data(package, &1))
    |> Enum.reject(&is_nil(&1))
    |> List.flatten()
  end

  defp build_data(package, "FS LOCAL CURRENCY") do
    {:ok, data} = XlsxReader.sheet(package, "FS LOCAL CURRENCY", number_type: Decimal)

    %{
      financial_statement_format: get_value(data, 0, 1),
      financial_statement_currency: get_value(data, 1, 1),
      periods: [
        %{
          balance_f_x: get_value(data, 4, 1),
          pl_f_x: get_value(data, 5, 1),
          period: get_value(data, 8, 1),
          statetment_as_of: get_value(data, 9, 1),
          units: get_value(data, 10, 1),
          cash: get_value(data, 16, 1),
          accounts_receivable_net: get_value(data, 17, 1),
          inventory: get_value(data, 18, 1),
          affiliates_advances: get_value(data, 19, 1),
          def_refundable_inc_tax: get_value(data, 20, 1),
          other_current_assets: get_value(data, 21, 1),
          prepaid: get_value(data, 22, 1),
          machinery_equipment: get_value(data, 28, 1),
          office_equipment: get_value(data, 29, 1),
          other_fixed_assets: get_value(data, 30, 1),
          transportation_equipment: get_value(data, 31, 1),
          real_state_buildings: get_value(data, 32, 1),
          less_accumulated_depr: get_value(data, 34, 1),
          due_from_affiliates: get_value(data, 38, 1),
          deferred_charges: get_value(data, 39, 1),
          intangible_goodwill: get_value(data, 40, 1),
          investment_others: get_value(data, 41, 1),
          other_assets_1: get_value(data, 42, 1),
          other_assets_2: get_value(data, 43, 1),
          bank_overdraft: get_value(data, 49, 1),
          accounts_payable: get_value(data, 50, 1),
          bank_payable: get_value(data, 51, 1),
          # tiene una suma extra
          other_current_liab: get_value(data, 52, 1),
          current_portion_ltd: get_value(data, 53, 1),
          bank_long_term_debt: get_value(data, 59, 1),
          other_lt_liabilities: get_value(data, 60, 1),
          subordinated_debt: get_value(data, 61, 1),
          common_stock: get_value(data, 69, 1),
          other: get_value(data, 70, 1),
          treasury_stock: get_value(data, 71, 1),
          retained_earnings: get_value(data, 72, 1),
          # Cual es la diferencia con el primer other?
          other_2: get_value(data, 73, 1),
          dividens_other: get_value(data, 74, 1),
          cash_flow_operation: get_value(data, 83, 1),
          revenue: get_value(data, 87, 1),
          less_return_allow: get_value(data, 88, 1),
          cost_goods_sold: get_value(data, 89, 1),
          cost_goods_other: get_value(data, 90, 1),
          salaries_wages: get_value(data, 94, 1),
          operating_experenses: get_value(data, 95, 1),
          selling_expense: get_value(data, 96, 1),
          other_selling_expense: get_value(data, 97, 1),
          bad_debt_expense: get_value(data, 98, 1),
          general_admin_exp: get_value(data, 99, 1),
          depreciation_expense: get_value(data, 100, 1),
          amortization_expense: get_value(data, 101, 1),
          interest_expense: get_value(data, 105, 1),
          non_recurring_expense: get_value(data, 106, 1),
          interest_income: get_value(data, 107, 1),
          other_income_expense: get_value(data, 108, 1),
          taxes: get_value(data, 112, 1)
        },
        %{
          balance_f_x: get_value(data, 4, 5),
          pl_f_x: get_value(data, 5, 5),
          period: get_value(data, 8, 5),
          statetment_as_of: get_value(data, 9, 5),
          units: get_value(data, 10, 5),
          cash: get_value(data, 16, 5),
          accounts_receivable_net: get_value(data, 17, 5),
          inventory: get_value(data, 18, 5),
          affiliates_advances: get_value(data, 19, 5),
          def_refundable_inc_tax: get_value(data, 20, 5),
          other_current_assets: get_value(data, 21, 5),
          prepaid: get_value(data, 22, 5),
          machinery_equipment: get_value(data, 28, 5),
          office_equipment: get_value(data, 29, 5),
          other_fixed_assets: get_value(data, 30, 5),
          transportation_equipment: get_value(data, 31, 5),
          real_state_buildings: get_value(data, 32, 5),
          less_accumulated_depr: get_value(data, 34, 5),
          due_from_affiliates: get_value(data, 38, 5),
          deferred_charges: get_value(data, 39, 5),
          intangible_goodwill: get_value(data, 40, 5),
          investment_others: get_value(data, 41, 5),
          other_assets_1: get_value(data, 42, 5),
          other_assets_2: get_value(data, 43, 5),
          bank_overdraft: get_value(data, 49, 5),
          accounts_payable: get_value(data, 50, 5),
          bank_payable: get_value(data, 51, 5),
          other_current_liab: get_value(data, 52, 5),
          current_portion_ltd: get_value(data, 53, 5),
          bank_long_term_debt: get_value(data, 59, 5),
          other_lt_liabilities: get_value(data, 60, 5),
          subordinated_debt: get_value(data, 61, 5),
          common_stock: get_value(data, 69, 5),
          other: get_value(data, 70, 5),
          treasury_stock: get_value(data, 71, 5),
          retained_earnings: get_value(data, 72, 5),
          other_2: get_value(data, 73, 5),
          dividens_other: get_value(data, 74, 5),
          cash_flow_operation: get_value(data, 83, 5),
          revenue: get_value(data, 87, 5),
          less_return_allow: get_value(data, 88, 5),
          cost_goods_sold: get_value(data, 89, 5),
          cost_goods_other: get_value(data, 90, 5),
          salaries_wages: get_value(data, 94, 5),
          operating_experenses: get_value(data, 95, 5),
          selling_expense: get_value(data, 96, 5),
          other_selling_expense: get_value(data, 97, 5),
          bad_debt_expense: get_value(data, 98, 5),
          general_admin_exp: get_value(data, 99, 5),
          depreciation_expense: get_value(data, 100, 5),
          amortization_expense: get_value(data, 101, 5),
          interest_expense: get_value(data, 105, 5),
          non_recurring_expense: get_value(data, 106, 5),
          interest_income: get_value(data, 107, 5),
          other_income_expense: get_value(data, 108, 5),
          taxes: get_value(data, 112, 5)
        },
        %{
          balance_f_x: get_value(data, 4, 9),
          pl_f_x: get_value(data, 5, 9),
          period: get_value(data, 8, 9),
          statetment_as_of: get_value(data, 9, 9),
          units: get_value(data, 10, 9),
          cash: get_value(data, 16, 9),
          accounts_receivable_net: get_value(data, 17, 9),
          inventory: get_value(data, 18, 9),
          affiliates_advances: get_value(data, 19, 9),
          def_refundable_inc_tax: get_value(data, 20, 9),
          other_current_assets: get_value(data, 21, 9),
          prepaid: get_value(data, 22, 9),
          machinery_equipment: get_value(data, 28, 9),
          office_equipment: get_value(data, 29, 9),
          other_fixed_assets: get_value(data, 30, 9),
          transportation_equipment: get_value(data, 31, 9),
          real_state_buildings: get_value(data, 32, 9),
          less_accumulated_depr: get_value(data, 34, 9),
          due_from_affiliates: get_value(data, 38, 9),
          deferred_charges: get_value(data, 39, 9),
          intangible_goodwill: get_value(data, 40, 9),
          investment_others: get_value(data, 41, 9),
          other_assets_1: get_value(data, 42, 9),
          other_assets_2: get_value(data, 43, 9),
          bank_overdraft: get_value(data, 49, 9),
          accounts_payable: get_value(data, 50, 9),
          bank_payable: get_value(data, 51, 9),
          other_current_liab: get_value(data, 52, 9),
          current_portion_ltd: get_value(data, 53, 9),
          bank_long_term_debt: get_value(data, 59, 9),
          other_lt_liabilities: get_value(data, 60, 9),
          subordinated_debt: get_value(data, 61, 9),
          common_stock: get_value(data, 69, 9),
          other: get_value(data, 70, 9),
          treasury_stock: get_value(data, 71, 9),
          retained_earnings: get_value(data, 72, 9),
          other_2: get_value(data, 73, 9),
          dividens_other: get_value(data, 74, 9),
          cash_flow_operation: get_value(data, 83, 9),
          revenue: get_value(data, 87, 9),
          less_return_allow: get_value(data, 88, 9),
          cost_goods_sold: get_value(data, 89, 9),
          cost_goods_other: get_value(data, 90, 9),
          salaries_wages: get_value(data, 94, 9),
          operating_experenses: get_value(data, 95, 9),
          selling_expense: get_value(data, 96, 9),
          other_selling_expense: get_value(data, 97, 9),
          bad_debt_expense: get_value(data, 98, 9),
          general_admin_exp: get_value(data, 99, 9),
          depreciation_expense: get_value(data, 100, 9),
          amortization_expense: get_value(data, 101, 9),
          interest_expense: get_value(data, 105, 9),
          non_recurring_expense: get_value(data, 106, 9),
          interest_income: get_value(data, 107, 9),
          other_income_expense: get_value(data, 108, 9),
          taxes: get_value(data, 112, 9)
        },
        %{
          balance_f_x: get_value(data, 4, 13),
          pl_f_x: get_value(data, 5, 13),
          period: get_value(data, 8, 13),
          statetment_as_of: get_value(data, 9, 13),
          units: get_value(data, 10, 13),
          cash: get_value(data, 16, 13),
          accounts_receivable_net: get_value(data, 17, 13),
          inventory: get_value(data, 18, 13),
          affiliates_advances: get_value(data, 19, 13),
          def_refundable_inc_tax: get_value(data, 20, 13),
          other_current_assets: get_value(data, 21, 13),
          prepaid: get_value(data, 22, 13),
          machinery_equipment: get_value(data, 28, 13),
          office_equipment: get_value(data, 29, 13),
          other_fixed_assets: get_value(data, 30, 13),
          transportation_equipment: get_value(data, 31, 13),
          real_state_buildings: get_value(data, 32, 13),
          less_accumulated_depr: get_value(data, 34, 13),
          due_from_affiliates: get_value(data, 38, 13),
          deferred_charges: get_value(data, 39, 13),
          intangible_goodwill: get_value(data, 40, 13),
          investment_others: get_value(data, 41, 13),
          other_assets_1: get_value(data, 42, 13),
          other_assets_2: get_value(data, 43, 13),
          bank_overdraft: get_value(data, 49, 13),
          accounts_payable: get_value(data, 50, 13),
          bank_payable: get_value(data, 51, 13),
          other_current_liab: get_value(data, 52, 13),
          current_portion_ltd: get_value(data, 53, 13),
          bank_long_term_debt: get_value(data, 59, 13),
          other_lt_liabilities: get_value(data, 60, 13),
          subordinated_debt: get_value(data, 61, 13),
          common_stock: get_value(data, 69, 13),
          other: get_value(data, 70, 13),
          treasury_stock: get_value(data, 71, 13),
          retained_earnings: get_value(data, 72, 13),
          other_2: get_value(data, 73, 13),
          dividens_other: get_value(data, 74, 13),
          cash_flow_operation: get_value(data, 83, 13),
          revenue: get_value(data, 87, 13),
          less_return_allow: get_value(data, 88, 13),
          cost_goods_sold: get_value(data, 89, 13),
          cost_goods_other: get_value(data, 90, 13),
          salaries_wages: get_value(data, 94, 13),
          operating_experenses: get_value(data, 95, 13),
          selling_expense: get_value(data, 96, 13),
          other_selling_expense: get_value(data, 97, 13),
          bad_debt_expense: get_value(data, 98, 13),
          general_admin_exp: get_value(data, 99, 13),
          depreciation_expense: get_value(data, 100, 13),
          amortization_expense: get_value(data, 101, 13),
          interest_expense: get_value(data, 105, 13),
          non_recurring_expense: get_value(data, 106, 13),
          interest_income: get_value(data, 107, 13),
          other_income_expense: get_value(data, 108, 13),
          taxes: get_value(data, 112, 13)
        },
        %{
          balance_f_x: get_value(data, 4, 17),
          pl_f_x: get_value(data, 5, 17),
          period: get_value(data, 8, 17),
          statetment_as_of: get_value(data, 9, 17),
          units: get_value(data, 10, 17),
          cash: get_value(data, 16, 17),
          accounts_receivable_net: get_value(data, 17, 17),
          inventory: get_value(data, 18, 17),
          affiliates_advances: get_value(data, 19, 17),
          def_refundable_inc_tax: get_value(data, 20, 17),
          other_current_assets: get_value(data, 21, 17),
          prepaid: get_value(data, 22, 17),
          machinery_equipment: get_value(data, 28, 17),
          office_equipment: get_value(data, 29, 17),
          other_fixed_assets: get_value(data, 30, 17),
          transportation_equipment: get_value(data, 31, 17),
          real_state_buildings: get_value(data, 32, 17),
          less_accumulated_depr: get_value(data, 34, 17),
          due_from_affiliates: get_value(data, 38, 17),
          deferred_charges: get_value(data, 39, 17),
          intangible_goodwill: get_value(data, 40, 17),
          investment_others: get_value(data, 41, 17),
          other_assets_1: get_value(data, 42, 17),
          other_assets_2: get_value(data, 43, 17),
          bank_overdraft: get_value(data, 49, 17),
          accounts_payable: get_value(data, 50, 17),
          bank_payable: get_value(data, 51, 17),
          other_current_liab: get_value(data, 52, 17),
          current_portion_ltd: get_value(data, 53, 17),
          bank_long_term_debt: get_value(data, 59, 17),
          other_lt_liabilities: get_value(data, 60, 17),
          subordinated_debt: get_value(data, 61, 17),
          common_stock: get_value(data, 69, 17),
          other: get_value(data, 70, 17),
          treasury_stock: get_value(data, 71, 17),
          retained_earnings: get_value(data, 72, 17),
          other_2: get_value(data, 73, 17),
          dividens_other: get_value(data, 74, 17),
          cash_flow_operation: get_value(data, 83, 17),
          revenue: get_value(data, 87, 17),
          less_return_allow: get_value(data, 88, 17),
          cost_goods_sold: get_value(data, 89, 17),
          cost_goods_other: get_value(data, 90, 17),
          salaries_wages: get_value(data, 94, 17),
          operating_experenses: get_value(data, 95, 17),
          selling_expense: get_value(data, 96, 17),
          other_selling_expense: get_value(data, 97, 17),
          bad_debt_expense: get_value(data, 98, 17),
          general_admin_exp: get_value(data, 99, 17),
          depreciation_expense: get_value(data, 100, 17),
          amortization_expense: get_value(data, 101, 17),
          interest_expense: get_value(data, 105, 17),
          non_recurring_expense: get_value(data, 106, 17),
          interest_income: get_value(data, 107, 17),
          other_income_expense: get_value(data, 108, 17),
          taxes: get_value(data, 112, 17)
        }
      ]
    }
  end

  defp build_data(package, "SUMMARY") do
    {:ok, [_title, _title_2 | data]} = XlsxReader.sheet(package, "SUMMARY", number_type: Decimal)

    %{
      template_version: get_value(data, 0, 1),
      financials_spread_by: get_value(data, 1, 1),
      sales_rep_name: get_value(data, 2, 1),
      customer_name: get_value(data, 4, 1),
      sap_number: get_value(data, 5, 1),
      customer_country: get_value(data, 6, 1),
      insurance_coverage: get_value(data, 8, 1),
      customer_since_month_year: get_value(data, 9, 1),
      customer_inception_year: get_value(data, 10, 1),
      customer_type: get_value(data, 11, 1),
      template_version_date: get_value(data, 0, 5),
      analysis_performed_by: get_value(data, 1, 5),
      review_date_month_year: get_value(data, 4, 5),
      next_review_date_month_year: get_value(data, 5, 5),
      review_period: get_value(data, 6, 5),
      financial_statement_info_from: get_value(data, 9, 5),
      current_limit: %{
        existing_credit_limit: get_value(data, 14, 1),
        insurance_coverage: get_value(data, 15, 1),
        coverage_type: get_value(data, 16, 1),
        insurance_company: get_value(data, 17, 1)
      },
      request_limit: %{
        credit_limit: get_value(data, 14, 5),
        insurance_coverage: get_value(data, 15, 5),
        coverage_type: get_value(data, 16, 5),
        insurance_company: get_value(data, 17, 5)
      },
      collateral_type: get_value(data, 20, 4),
      amount: get_value(data, 20, 5),
      expiration_date: get_value(data, 20, 6),
      dra: get_value(data, 23, 5),
      recommended_limit: get_value(data, 23, 6),
      long_term_foreign_currency: get_value(data, 25, 5),
      outlook: get_value(data, 25, 6),
      summary: get_value(data, 52, 0)
    }
  end

  defp build_data(_package, _), do: nil

  defp get_value(data, row, column) do
    data |> Enum.at(row) |> Enum.at(column)
  end
end
